"""empty message

Revision ID: 171cad101c85
Revises: 
Create Date: 2024-05-06 03:10:48.997313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171cad101c85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('g_auth_verify', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('chameleon',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sex', sa.String(length=200), nullable=True),
    sa.Column('dob', sa.String(length=200), nullable=True),
    sa.Column('dod', sa.String(length=200), nullable=True),
    sa.Column('dams_sire', sa.String(length=200), nullable=True),
    sa.Column('sire', sa.String(length=200), nullable=True),
    sa.Column('dams', sa.String(length=200), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chameleon')
    op.drop_table('user')
    # ### end Alembic commands ###
